project:
  type: website

website:
  title: "Ars Metrica"
  navbar:
    logo: logo.png
    right:
      - icon: github
        href: https://github.com/andeliton
      - icon: linkedin
        href: https://linkedin.com/andeliton-soares-95a464337
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Sobre"
        href: about.qmd
      - text: "An√°lises"  # <--- E ISSO
        href: analise.qmd   # <--- ADICIONE ISSO
   

format:
  html:
    theme:
      light: lux      # Tema elegante (serifado)
      dark: cyborg    # Tema high-tech (fundo preto)
    css: styles.css
    toc: true